### ISSUE TITLE
Is pyasn1 v0.4.8 is compatible with python3.11

### ISSUE THREAD

**Issue by vivek-crest** [pyasn1/pyasn1#26]
The [Pypi documentation](https://pypi.org/project/pyasn1/) mentions that pyasn1 v0.4.8 is compatible with Python 3.
Does this claim that the library is compatible with Python 3.11.x as well?
If not, is there a plan to release a Python 3.11.x compatible version?

**Comment by droideck** [comment]
There's a plan to release the new Python 3.11.x compatible version:
https://pypi.org/project/pyasn1/0.5.0rc2/

Soon!
