### ISSUE TITLE
Leave RCs and betas published as tags.

### ISSUE THREAD

**Issue by macieyng** [pyasn1/pyasn1#31]
4 days ago version 0.5.0.rc2 was released as 0.5.0. One of our dependencies is using 0.5.0.rc2 and since Friday it cannot be installed, because 0.5.0.rc2 no longer exists, so we have to wait for maintainers of that dependency to patch their packages, so it can be installed in our project correctly. 

I want to ask you if it's possible to leave 0.5.0.rc2 as tagged release. 

Thanks in advance!

**Comment by macieyng** [comment]
@droideck @tiran

**Comment by droideck** [comment]
The correct way would be to update it on the dependency site, and I want to avoid creating confusion by resurrecting 0.5.0.rc2.

0.5.0.rc2 was intended to be used for testing purposes as any pre-release (so it was not a production-ready version).
So it's more of a temporary inconvenience other than the system-breaking issue.
