### ISSUE TITLE
Replace links to snmplabs.com

### ISSUE THREAD

**Issue by tiran** [pyasn1/pyasn1#4]
It seems like Ilya no longer owns the domain ``snmplabs.com``. It is now owned by a domain grabber.

I suggest that we replace all links to point to https://pyasn1.readthedocs.io/ instead.

**Comment by lextm** [comment]
I think merging ASN.1 docs with https://www.pysnmp.com might be a good choice, but leaving them on https://pyasn1.readthedocs.io/ is also nice if you plan to maintain separately.

Will ping back once more progress is made on my side.

**Comment by lextm** [comment]
After cleaning up the repos as a whole, I think your proposed changes of "replace all links to point to https://pyasn1.readthedocs.io/ instead" is very simple. The asn1 and asn1-modules repos only use the links to point to license.html or documentation site itself.
