### ISSUE TITLE
When was `pyasn1==0.5.0rc2` discontinued?

### ISSUE THREAD

**Issue by kartikeyporwal** [pyasn1/pyasn1#45]
I've version `pyasn1==0.5.0rc2` in my `Pipfile.lock`, it's has been there quite sometime. When I tried to rebuilt my Docker image today again, I'm getting

`[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement pyasn1==0.5.0rc2 (from versions: 0.0.9a0, 0.0.10a0, 0.0.11a0, 0.0.12a0, 0.0.13a0, 0.0.13b0, 0.0.13, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.1, 0.2.2, 0.2.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.5.0)`

When I looked at https://pypi.org/project/pyasn1/#history, I did not find any details of version `0.5.0rc2`. I'm wondering when was `0.5.0rc2` removed from Pypi?

Thanks

**Comment by droideck** [comment]
Closing as duplicate:
https://github.com/pyasn1/pyasn1/issues/31

P.S. but yes, you are correct in your message.
