### ISSUE TITLE
TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by mikhailantoshkin** [pyasn1/pyasn1#52]
This is a duplicate of https://github.com/etingof/pyasn1/issues/178, since it is still present in this fork. 

The problem arises when [this](https://github.com/pyasn1/pyasn1/blob/e4f92449e189ce070203b94af29b256bec9a5152/pyasn1/type/univ.py#L2043) check succeeds during [this](https://github.com/pyasn1/pyasn1/blob/e4f92449e189ce070203b94af29b256bec9a5152/pyasn1/codec/ber/encoder.py#L649) call and bool is raised instead of Exception.

**Comment by FlorentClarret** [comment]
I'm also running into this problem. Note that this also could happen [here](https://github.com/pyasn1/pyasn1/blob/e4f92449e189ce070203b94af29b256bec9a5152/pyasn1/codec/ber/encoder.py#L541-L543) I believe
