### ISSUE TITLE
`https://pyasn1.readthedocs.io/en/latest/` does not work

### ISSUE THREAD

**Issue by lextm** [pyasn1/pyasn1#58]
Not sure if ReadTheDocs changed their server settings, but `https://pyasn1.readthedocs.io/en/latest/` does not work and shows a 404 error page.

However, individual pages like `https://pyasn1.readthedocs.io/en/latest/pyasn1/codec/native/contents.html` work.

**Comment by droideck** [comment]
https://pyasn1.readthedocs.io/en/latest/pyasn1/contents.html link opens without an issue.
And it's the link we have in our README.md:
https://github.com/pyasn1/pyasn1/blob/main/README.md?plain=1#L167

**Comment by lextm** [comment]
But this link will trigger the 404 unfortunately,

<img width="428" alt="Screenshot 2024-03-20 at 10 31 26 AM" src="https://github.com/pyasn1/pyasn1/assets/425130/e47c0a2a-b6aa-43d0-92a8-12d5ae0a8b1c">

Note that most other projects on ReadTheDocs do configure their default pages properly to make sure such links work. It is just inconvenient that yours doesn't.

**Comment by antoni-szych-rtbhouse** [comment]
Also note that https://pyasn1.readthedocs.io/en/latest/changelog.html seems to be not built from current version 0.6.0.
